// #Sireum

package bc

import org.sireum._
import art._
import art.PortMode._
import art.DispatchPropertyProtocol._
import art.Art.BridgeId._
import art.Art.PortId._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Arch {
  val BoilerControlSystem_i_Instance_bcproc_boiler : bc.BoilerControl.Boiler_i_bcproc_boiler_Bridge = {
    val opMode = Port[BoilerControl.OpMode.Type] (id = portId"0", name = "BoilerControlSystem_i_Instance_bcproc_boiler_opMode", mode = EventIn)
    val programReady = Port[art.Empty] (id = portId"1", name = "BoilerControlSystem_i_Instance_bcproc_boiler_programReady", mode = EventIn)
    val valve = Port[art.Empty] (id = portId"2", name = "BoilerControlSystem_i_Instance_bcproc_boiler_valve", mode = EventIn)
    val waiting = Port[art.Empty] (id = portId"3", name = "BoilerControlSystem_i_Instance_bcproc_boiler_waiting", mode = EventOut)
    val ready = Port[art.Empty] (id = portId"4", name = "BoilerControlSystem_i_Instance_bcproc_boiler_ready", mode = EventOut)

    bc.BoilerControl.Boiler_i_bcproc_boiler_Bridge(
      id = bridgeId"0",
      name = "BoilerControlSystem_i_Instance_bcproc_boiler",
      dispatchProtocol = Periodic(period = 5000),
      dispatchTriggers = None(),

      opMode = opMode,
      programReady = programReady,
      valve = valve,
      waiting = waiting,
      ready = ready
    )
  }
  val BoilerControlSystem_i_Instance_bcproc_pumpControl0 : bc.BoilerControl.PumpControl_i_bcproc_pumpControl0_Bridge = {
    val opMode = Port[BoilerControl.OpMode.Type] (id = portId"5", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl0_opMode", mode = EventIn)
    val openPump = Port[Base_Types.Boolean] (id = portId"6", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl0_openPump", mode = EventIn)
    val pumpOpen = Port[Base_Types.Boolean] (id = portId"7", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl0_pumpOpen", mode = EventOut)
    val pumpFlow = Port[Base_Types.Boolean] (id = portId"8", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl0_pumpFlow", mode = EventOut)
    val programReady = Port[art.Empty] (id = portId"9", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl0_programReady", mode = EventIn)
    val ready = Port[art.Empty] (id = portId"10", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl0_ready", mode = EventOut)

    bc.BoilerControl.PumpControl_i_bcproc_pumpControl0_Bridge(
      id = bridgeId"1",
      name = "BoilerControlSystem_i_Instance_bcproc_pumpControl0",
      dispatchProtocol = Periodic(period = 5000),
      dispatchTriggers = None(),

      opMode = opMode,
      openPump = openPump,
      pumpOpen = pumpOpen,
      pumpFlow = pumpFlow,
      programReady = programReady,
      ready = ready
    )
  }
  val BoilerControlSystem_i_Instance_bcproc_pumpControl1 : bc.BoilerControl.PumpControl_i_bcproc_pumpControl1_Bridge = {
    val opMode = Port[BoilerControl.OpMode.Type] (id = portId"11", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl1_opMode", mode = EventIn)
    val openPump = Port[Base_Types.Boolean] (id = portId"12", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl1_openPump", mode = EventIn)
    val pumpOpen = Port[Base_Types.Boolean] (id = portId"13", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl1_pumpOpen", mode = EventOut)
    val pumpFlow = Port[Base_Types.Boolean] (id = portId"14", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl1_pumpFlow", mode = EventOut)
    val programReady = Port[art.Empty] (id = portId"15", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl1_programReady", mode = EventIn)
    val ready = Port[art.Empty] (id = portId"16", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl1_ready", mode = EventOut)

    bc.BoilerControl.PumpControl_i_bcproc_pumpControl1_Bridge(
      id = bridgeId"2",
      name = "BoilerControlSystem_i_Instance_bcproc_pumpControl1",
      dispatchProtocol = Periodic(period = 5000),
      dispatchTriggers = None(),

      opMode = opMode,
      openPump = openPump,
      pumpOpen = pumpOpen,
      pumpFlow = pumpFlow,
      programReady = programReady,
      ready = ready
    )
  }
  val BoilerControlSystem_i_Instance_bcproc_pumpControl2 : bc.BoilerControl.PumpControl_i_bcproc_pumpControl2_Bridge = {
    val opMode = Port[BoilerControl.OpMode.Type] (id = portId"17", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl2_opMode", mode = EventIn)
    val openPump = Port[Base_Types.Boolean] (id = portId"18", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl2_openPump", mode = EventIn)
    val pumpOpen = Port[Base_Types.Boolean] (id = portId"19", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl2_pumpOpen", mode = EventOut)
    val pumpFlow = Port[Base_Types.Boolean] (id = portId"20", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl2_pumpFlow", mode = EventOut)
    val programReady = Port[art.Empty] (id = portId"21", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl2_programReady", mode = EventIn)
    val ready = Port[art.Empty] (id = portId"22", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl2_ready", mode = EventOut)

    bc.BoilerControl.PumpControl_i_bcproc_pumpControl2_Bridge(
      id = bridgeId"3",
      name = "BoilerControlSystem_i_Instance_bcproc_pumpControl2",
      dispatchProtocol = Periodic(period = 5000),
      dispatchTriggers = None(),

      opMode = opMode,
      openPump = openPump,
      pumpOpen = pumpOpen,
      pumpFlow = pumpFlow,
      programReady = programReady,
      ready = ready
    )
  }
  val BoilerControlSystem_i_Instance_bcproc_pumpControl3 : bc.BoilerControl.PumpControl_i_bcproc_pumpControl3_Bridge = {
    val opMode = Port[BoilerControl.OpMode.Type] (id = portId"23", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl3_opMode", mode = EventIn)
    val openPump = Port[Base_Types.Boolean] (id = portId"24", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl3_openPump", mode = EventIn)
    val pumpOpen = Port[Base_Types.Boolean] (id = portId"25", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl3_pumpOpen", mode = EventOut)
    val pumpFlow = Port[Base_Types.Boolean] (id = portId"26", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl3_pumpFlow", mode = EventOut)
    val programReady = Port[art.Empty] (id = portId"27", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl3_programReady", mode = EventIn)
    val ready = Port[art.Empty] (id = portId"28", name = "BoilerControlSystem_i_Instance_bcproc_pumpControl3_ready", mode = EventOut)

    bc.BoilerControl.PumpControl_i_bcproc_pumpControl3_Bridge(
      id = bridgeId"4",
      name = "BoilerControlSystem_i_Instance_bcproc_pumpControl3",
      dispatchProtocol = Periodic(period = 5000),
      dispatchTriggers = None(),

      opMode = opMode,
      openPump = openPump,
      pumpOpen = pumpOpen,
      pumpFlow = pumpFlow,
      programReady = programReady,
      ready = ready
    )
  }
  val BoilerControlSystem_i_Instance_bcproc_waterMeter : bc.BoilerControl.WaterMeter_i_bcproc_waterMeter_Bridge = {
    val opMode = Port[BoilerControl.OpMode.Type] (id = portId"29", name = "BoilerControlSystem_i_Instance_bcproc_waterMeter_opMode", mode = EventIn)
    val level = Port[Base_Types.Float_32] (id = portId"30", name = "BoilerControlSystem_i_Instance_bcproc_waterMeter_level", mode = EventOut)
    val programReady = Port[art.Empty] (id = portId"31", name = "BoilerControlSystem_i_Instance_bcproc_waterMeter_programReady", mode = EventIn)
    val ready = Port[art.Empty] (id = portId"32", name = "BoilerControlSystem_i_Instance_bcproc_waterMeter_ready", mode = EventOut)

    bc.BoilerControl.WaterMeter_i_bcproc_waterMeter_Bridge(
      id = bridgeId"5",
      name = "BoilerControlSystem_i_Instance_bcproc_waterMeter",
      dispatchProtocol = Periodic(period = 5000),
      dispatchTriggers = None(),

      opMode = opMode,
      level = level,
      programReady = programReady,
      ready = ready
    )
  }
  val BoilerControlSystem_i_Instance_bcproc_steamMeter : bc.BoilerControl.SteamMeter_i_bcproc_steamMeter_Bridge = {
    val opMode = Port[BoilerControl.OpMode.Type] (id = portId"33", name = "BoilerControlSystem_i_Instance_bcproc_steamMeter_opMode", mode = EventIn)
    val rate = Port[Base_Types.Float_32] (id = portId"34", name = "BoilerControlSystem_i_Instance_bcproc_steamMeter_rate", mode = EventOut)
    val programReady = Port[art.Empty] (id = portId"35", name = "BoilerControlSystem_i_Instance_bcproc_steamMeter_programReady", mode = EventIn)
    val ready = Port[art.Empty] (id = portId"36", name = "BoilerControlSystem_i_Instance_bcproc_steamMeter_ready", mode = EventOut)

    bc.BoilerControl.SteamMeter_i_bcproc_steamMeter_Bridge(
      id = bridgeId"6",
      name = "BoilerControlSystem_i_Instance_bcproc_steamMeter",
      dispatchProtocol = Periodic(period = 5000),
      dispatchTriggers = None(),

      opMode = opMode,
      rate = rate,
      programReady = programReady,
      ready = ready
    )
  }
  val BoilerControlSystem_i_Instance_bcproc_desk : bc.BoilerControl.OperatorDesk_i_bcproc_desk_Bridge = {
    val opMode = Port[BoilerControl.OpMode.Type] (id = portId"37", name = "BoilerControlSystem_i_Instance_bcproc_desk_opMode", mode = EventIn)
    val pumpFail0 = Port[art.Empty] (id = portId"38", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpFail0", mode = EventIn)
    val pumpFail1 = Port[art.Empty] (id = portId"39", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpFail1", mode = EventIn)
    val pumpFail2 = Port[art.Empty] (id = portId"40", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpFail2", mode = EventIn)
    val pumpFail3 = Port[art.Empty] (id = portId"41", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpFail3", mode = EventIn)
    val pumpControlFail0 = Port[art.Empty] (id = portId"42", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlFail0", mode = EventIn)
    val pumpControlFail1 = Port[art.Empty] (id = portId"43", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlFail1", mode = EventIn)
    val pumpControlFail2 = Port[art.Empty] (id = portId"44", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlFail2", mode = EventIn)
    val pumpControlFail3 = Port[art.Empty] (id = portId"45", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlFail3", mode = EventIn)
    val levelFail = Port[art.Empty] (id = portId"46", name = "BoilerControlSystem_i_Instance_bcproc_desk_levelFail", mode = EventIn)
    val steamFail = Port[art.Empty] (id = portId"47", name = "BoilerControlSystem_i_Instance_bcproc_desk_steamFail", mode = EventIn)
    val pumpRepairAck0 = Port[art.Empty] (id = portId"48", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpRepairAck0", mode = EventIn)
    val pumpRepairAck1 = Port[art.Empty] (id = portId"49", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpRepairAck1", mode = EventIn)
    val pumpRepairAck2 = Port[art.Empty] (id = portId"50", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpRepairAck2", mode = EventIn)
    val pumpRepairAck3 = Port[art.Empty] (id = portId"51", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpRepairAck3", mode = EventIn)
    val pumpControlRepairAck0 = Port[art.Empty] (id = portId"52", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlRepairAck0", mode = EventIn)
    val pumpControlRepairAck1 = Port[art.Empty] (id = portId"53", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlRepairAck1", mode = EventIn)
    val pumpControlRepairAck2 = Port[art.Empty] (id = portId"54", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlRepairAck2", mode = EventIn)
    val pumpControlRepairAck3 = Port[art.Empty] (id = portId"55", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlRepairAck3", mode = EventIn)
    val levelRepairAck = Port[art.Empty] (id = portId"56", name = "BoilerControlSystem_i_Instance_bcproc_desk_levelRepairAck", mode = EventIn)
    val steamRepairAck = Port[art.Empty] (id = portId"57", name = "BoilerControlSystem_i_Instance_bcproc_desk_steamRepairAck", mode = EventIn)
    val stop = Port[art.Empty] (id = portId"58", name = "BoilerControlSystem_i_Instance_bcproc_desk_stop", mode = EventOut)
    val pumpRepair0 = Port[art.Empty] (id = portId"59", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpRepair0", mode = EventOut)
    val pumpRepair1 = Port[art.Empty] (id = portId"60", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpRepair1", mode = EventOut)
    val pumpRepair2 = Port[art.Empty] (id = portId"61", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpRepair2", mode = EventOut)
    val pumpRepair3 = Port[art.Empty] (id = portId"62", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpRepair3", mode = EventOut)
    val pumpControlRepair0 = Port[art.Empty] (id = portId"63", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlRepair0", mode = EventOut)
    val pumpControlRepair1 = Port[art.Empty] (id = portId"64", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlRepair1", mode = EventOut)
    val pumpControlRepair2 = Port[art.Empty] (id = portId"65", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlRepair2", mode = EventOut)
    val pumpControlRepair3 = Port[art.Empty] (id = portId"66", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlRepair3", mode = EventOut)
    val levelRepair = Port[art.Empty] (id = portId"67", name = "BoilerControlSystem_i_Instance_bcproc_desk_levelRepair", mode = EventOut)
    val steamRepair = Port[art.Empty] (id = portId"68", name = "BoilerControlSystem_i_Instance_bcproc_desk_steamRepair", mode = EventOut)
    val pumpFailAck0 = Port[art.Empty] (id = portId"69", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpFailAck0", mode = EventOut)
    val pumpFailAck1 = Port[art.Empty] (id = portId"70", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpFailAck1", mode = EventOut)
    val pumpFailAck2 = Port[art.Empty] (id = portId"71", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpFailAck2", mode = EventOut)
    val pumpFailAck3 = Port[art.Empty] (id = portId"72", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpFailAck3", mode = EventOut)
    val pumpControlFailAck0 = Port[art.Empty] (id = portId"73", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlFailAck0", mode = EventOut)
    val pumpControlFailAck1 = Port[art.Empty] (id = portId"74", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlFailAck1", mode = EventOut)
    val pumpControlFailAck2 = Port[art.Empty] (id = portId"75", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlFailAck2", mode = EventOut)
    val pumpControlFailAck3 = Port[art.Empty] (id = portId"76", name = "BoilerControlSystem_i_Instance_bcproc_desk_pumpControlFailAck3", mode = EventOut)
    val levelFailAck = Port[art.Empty] (id = portId"77", name = "BoilerControlSystem_i_Instance_bcproc_desk_levelFailAck", mode = EventOut)
    val steamFailAck = Port[art.Empty] (id = portId"78", name = "BoilerControlSystem_i_Instance_bcproc_desk_steamFailAck", mode = EventOut)

    bc.BoilerControl.OperatorDesk_i_bcproc_desk_Bridge(
      id = bridgeId"7",
      name = "BoilerControlSystem_i_Instance_bcproc_desk",
      dispatchProtocol = Periodic(period = 5000),
      dispatchTriggers = None(),

      opMode = opMode,
      pumpFail0 = pumpFail0,
      pumpFail1 = pumpFail1,
      pumpFail2 = pumpFail2,
      pumpFail3 = pumpFail3,
      pumpControlFail0 = pumpControlFail0,
      pumpControlFail1 = pumpControlFail1,
      pumpControlFail2 = pumpControlFail2,
      pumpControlFail3 = pumpControlFail3,
      levelFail = levelFail,
      steamFail = steamFail,
      pumpRepairAck0 = pumpRepairAck0,
      pumpRepairAck1 = pumpRepairAck1,
      pumpRepairAck2 = pumpRepairAck2,
      pumpRepairAck3 = pumpRepairAck3,
      pumpControlRepairAck0 = pumpControlRepairAck0,
      pumpControlRepairAck1 = pumpControlRepairAck1,
      pumpControlRepairAck2 = pumpControlRepairAck2,
      pumpControlRepairAck3 = pumpControlRepairAck3,
      levelRepairAck = levelRepairAck,
      steamRepairAck = steamRepairAck,
      stop = stop,
      pumpRepair0 = pumpRepair0,
      pumpRepair1 = pumpRepair1,
      pumpRepair2 = pumpRepair2,
      pumpRepair3 = pumpRepair3,
      pumpControlRepair0 = pumpControlRepair0,
      pumpControlRepair1 = pumpControlRepair1,
      pumpControlRepair2 = pumpControlRepair2,
      pumpControlRepair3 = pumpControlRepair3,
      levelRepair = levelRepair,
      steamRepair = steamRepair,
      pumpFailAck0 = pumpFailAck0,
      pumpFailAck1 = pumpFailAck1,
      pumpFailAck2 = pumpFailAck2,
      pumpFailAck3 = pumpFailAck3,
      pumpControlFailAck0 = pumpControlFailAck0,
      pumpControlFailAck1 = pumpControlFailAck1,
      pumpControlFailAck2 = pumpControlFailAck2,
      pumpControlFailAck3 = pumpControlFailAck3,
      levelFailAck = levelFailAck,
      steamFailAck = steamFailAck
    )
  }
  val BoilerControlSystem_i_Instance_bcproc_control : bc.BoilerControl.BoilerControl_i_bcproc_control_Bridge = {
    val pumpOpen0 = Port[Base_Types.Boolean] (id = portId"79", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpOpen0", mode = EventIn)
    val pumpOpen1 = Port[Base_Types.Boolean] (id = portId"80", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpOpen1", mode = EventIn)
    val pumpOpen2 = Port[Base_Types.Boolean] (id = portId"81", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpOpen2", mode = EventIn)
    val pumpOpen3 = Port[Base_Types.Boolean] (id = portId"82", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpOpen3", mode = EventIn)
    val pumpFlow0 = Port[Base_Types.Boolean] (id = portId"83", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpFlow0", mode = EventIn)
    val pumpFlow1 = Port[Base_Types.Boolean] (id = portId"84", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpFlow1", mode = EventIn)
    val pumpFlow2 = Port[Base_Types.Boolean] (id = portId"85", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpFlow2", mode = EventIn)
    val pumpFlow3 = Port[Base_Types.Boolean] (id = portId"86", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpFlow3", mode = EventIn)
    val waterLevel = Port[Base_Types.Float_32] (id = portId"87", name = "BoilerControlSystem_i_Instance_bcproc_control_waterLevel", mode = EventIn)
    val steamRate = Port[Base_Types.Float_32] (id = portId"88", name = "BoilerControlSystem_i_Instance_bcproc_control_steamRate", mode = EventIn)
    val opMode = Port[BoilerControl.OpMode.Type] (id = portId"89", name = "BoilerControlSystem_i_Instance_bcproc_control_opMode", mode = EventOut)
    val openPump0 = Port[Base_Types.Boolean] (id = portId"90", name = "BoilerControlSystem_i_Instance_bcproc_control_openPump0", mode = EventOut)
    val openPump1 = Port[Base_Types.Boolean] (id = portId"91", name = "BoilerControlSystem_i_Instance_bcproc_control_openPump1", mode = EventOut)
    val openPump2 = Port[Base_Types.Boolean] (id = portId"92", name = "BoilerControlSystem_i_Instance_bcproc_control_openPump2", mode = EventOut)
    val openPump3 = Port[Base_Types.Boolean] (id = portId"93", name = "BoilerControlSystem_i_Instance_bcproc_control_openPump3", mode = EventOut)
    val stop = Port[art.Empty] (id = portId"94", name = "BoilerControlSystem_i_Instance_bcproc_control_stop", mode = EventIn)
    val boilerWaiting = Port[art.Empty] (id = portId"95", name = "BoilerControlSystem_i_Instance_bcproc_control_boilerWaiting", mode = EventIn)
    val boilerReady = Port[art.Empty] (id = portId"96", name = "BoilerControlSystem_i_Instance_bcproc_control_boilerReady", mode = EventIn)
    val waterMeterReady = Port[art.Empty] (id = portId"97", name = "BoilerControlSystem_i_Instance_bcproc_control_waterMeterReady", mode = EventIn)
    val pumpControlReady0 = Port[art.Empty] (id = portId"98", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlReady0", mode = EventIn)
    val pumpControlReady1 = Port[art.Empty] (id = portId"99", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlReady1", mode = EventIn)
    val pumpControlReady2 = Port[art.Empty] (id = portId"100", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlReady2", mode = EventIn)
    val pumpControlReady3 = Port[art.Empty] (id = portId"101", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlReady3", mode = EventIn)
    val steamMeterReady = Port[art.Empty] (id = portId"102", name = "BoilerControlSystem_i_Instance_bcproc_control_steamMeterReady", mode = EventIn)
    val pumpRepair0 = Port[art.Empty] (id = portId"103", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpRepair0", mode = EventIn)
    val pumpRepair1 = Port[art.Empty] (id = portId"104", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpRepair1", mode = EventIn)
    val pumpRepair2 = Port[art.Empty] (id = portId"105", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpRepair2", mode = EventIn)
    val pumpRepair3 = Port[art.Empty] (id = portId"106", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpRepair3", mode = EventIn)
    val pumpControlRepair0 = Port[art.Empty] (id = portId"107", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlRepair0", mode = EventIn)
    val pumpControlRepair1 = Port[art.Empty] (id = portId"108", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlRepair1", mode = EventIn)
    val pumpControlRepair2 = Port[art.Empty] (id = portId"109", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlRepair2", mode = EventIn)
    val pumpControlRepair3 = Port[art.Empty] (id = portId"110", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlRepair3", mode = EventIn)
    val levelRepair = Port[art.Empty] (id = portId"111", name = "BoilerControlSystem_i_Instance_bcproc_control_levelRepair", mode = EventIn)
    val steamRepair = Port[art.Empty] (id = portId"112", name = "BoilerControlSystem_i_Instance_bcproc_control_steamRepair", mode = EventIn)
    val pumpFailAck0 = Port[art.Empty] (id = portId"113", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpFailAck0", mode = EventIn)
    val pumpFailAck1 = Port[art.Empty] (id = portId"114", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpFailAck1", mode = EventIn)
    val pumpFailAck2 = Port[art.Empty] (id = portId"115", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpFailAck2", mode = EventIn)
    val pumpFailAck3 = Port[art.Empty] (id = portId"116", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpFailAck3", mode = EventIn)
    val pumpControlFailAck0 = Port[art.Empty] (id = portId"117", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlFailAck0", mode = EventIn)
    val pumpControlFailAck1 = Port[art.Empty] (id = portId"118", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlFailAck1", mode = EventIn)
    val pumpControlFailAck2 = Port[art.Empty] (id = portId"119", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlFailAck2", mode = EventIn)
    val pumpControlFailAck3 = Port[art.Empty] (id = portId"120", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlFailAck3", mode = EventIn)
    val levelFailAck = Port[art.Empty] (id = portId"121", name = "BoilerControlSystem_i_Instance_bcproc_control_levelFailAck", mode = EventIn)
    val steamFailAck = Port[art.Empty] (id = portId"122", name = "BoilerControlSystem_i_Instance_bcproc_control_steamFailAck", mode = EventIn)
    val ready = Port[art.Empty] (id = portId"123", name = "BoilerControlSystem_i_Instance_bcproc_control_ready", mode = EventOut)
    val valve = Port[art.Empty] (id = portId"124", name = "BoilerControlSystem_i_Instance_bcproc_control_valve", mode = EventOut)
    val pumpFail0 = Port[art.Empty] (id = portId"125", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpFail0", mode = EventOut)
    val pumpFail1 = Port[art.Empty] (id = portId"126", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpFail1", mode = EventOut)
    val pumpFail2 = Port[art.Empty] (id = portId"127", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpFail2", mode = EventOut)
    val pumpFail3 = Port[art.Empty] (id = portId"128", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpFail3", mode = EventOut)
    val pumpControlFail0 = Port[art.Empty] (id = portId"129", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlFail0", mode = EventOut)
    val pumpControlFail1 = Port[art.Empty] (id = portId"130", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlFail1", mode = EventOut)
    val pumpControlFail2 = Port[art.Empty] (id = portId"131", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlFail2", mode = EventOut)
    val pumpControlFail3 = Port[art.Empty] (id = portId"132", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlFail3", mode = EventOut)
    val levelFail = Port[art.Empty] (id = portId"133", name = "BoilerControlSystem_i_Instance_bcproc_control_levelFail", mode = EventOut)
    val steamFail = Port[art.Empty] (id = portId"134", name = "BoilerControlSystem_i_Instance_bcproc_control_steamFail", mode = EventOut)
    val pumpRepairAck0 = Port[art.Empty] (id = portId"135", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpRepairAck0", mode = EventOut)
    val pumpRepairAck1 = Port[art.Empty] (id = portId"136", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpRepairAck1", mode = EventOut)
    val pumpRepairAck2 = Port[art.Empty] (id = portId"137", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpRepairAck2", mode = EventOut)
    val pumpRepairAck3 = Port[art.Empty] (id = portId"138", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpRepairAck3", mode = EventOut)
    val pumpControlRepairAck0 = Port[art.Empty] (id = portId"139", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlRepairAck0", mode = EventOut)
    val pumpControlRepairAck1 = Port[art.Empty] (id = portId"140", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlRepairAck1", mode = EventOut)
    val pumpControlRepairAck2 = Port[art.Empty] (id = portId"141", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlRepairAck2", mode = EventOut)
    val pumpControlRepairAck3 = Port[art.Empty] (id = portId"142", name = "BoilerControlSystem_i_Instance_bcproc_control_pumpControlRepairAck3", mode = EventOut)
    val levelRepairAck = Port[art.Empty] (id = portId"143", name = "BoilerControlSystem_i_Instance_bcproc_control_levelRepairAck", mode = EventOut)
    val steamRepairAck = Port[art.Empty] (id = portId"144", name = "BoilerControlSystem_i_Instance_bcproc_control_steamRepairAck", mode = EventOut)

    bc.BoilerControl.BoilerControl_i_bcproc_control_Bridge(
      id = bridgeId"8",
      name = "BoilerControlSystem_i_Instance_bcproc_control",
      dispatchProtocol = Periodic(period = 5000),
      dispatchTriggers = None(),

      pumpOpen0 = pumpOpen0,
      pumpOpen1 = pumpOpen1,
      pumpOpen2 = pumpOpen2,
      pumpOpen3 = pumpOpen3,
      pumpFlow0 = pumpFlow0,
      pumpFlow1 = pumpFlow1,
      pumpFlow2 = pumpFlow2,
      pumpFlow3 = pumpFlow3,
      waterLevel = waterLevel,
      steamRate = steamRate,
      opMode = opMode,
      openPump0 = openPump0,
      openPump1 = openPump1,
      openPump2 = openPump2,
      openPump3 = openPump3,
      stop = stop,
      boilerWaiting = boilerWaiting,
      boilerReady = boilerReady,
      waterMeterReady = waterMeterReady,
      pumpControlReady0 = pumpControlReady0,
      pumpControlReady1 = pumpControlReady1,
      pumpControlReady2 = pumpControlReady2,
      pumpControlReady3 = pumpControlReady3,
      steamMeterReady = steamMeterReady,
      pumpRepair0 = pumpRepair0,
      pumpRepair1 = pumpRepair1,
      pumpRepair2 = pumpRepair2,
      pumpRepair3 = pumpRepair3,
      pumpControlRepair0 = pumpControlRepair0,
      pumpControlRepair1 = pumpControlRepair1,
      pumpControlRepair2 = pumpControlRepair2,
      pumpControlRepair3 = pumpControlRepair3,
      levelRepair = levelRepair,
      steamRepair = steamRepair,
      pumpFailAck0 = pumpFailAck0,
      pumpFailAck1 = pumpFailAck1,
      pumpFailAck2 = pumpFailAck2,
      pumpFailAck3 = pumpFailAck3,
      pumpControlFailAck0 = pumpControlFailAck0,
      pumpControlFailAck1 = pumpControlFailAck1,
      pumpControlFailAck2 = pumpControlFailAck2,
      pumpControlFailAck3 = pumpControlFailAck3,
      levelFailAck = levelFailAck,
      steamFailAck = steamFailAck,
      ready = ready,
      valve = valve,
      pumpFail0 = pumpFail0,
      pumpFail1 = pumpFail1,
      pumpFail2 = pumpFail2,
      pumpFail3 = pumpFail3,
      pumpControlFail0 = pumpControlFail0,
      pumpControlFail1 = pumpControlFail1,
      pumpControlFail2 = pumpControlFail2,
      pumpControlFail3 = pumpControlFail3,
      levelFail = levelFail,
      steamFail = steamFail,
      pumpRepairAck0 = pumpRepairAck0,
      pumpRepairAck1 = pumpRepairAck1,
      pumpRepairAck2 = pumpRepairAck2,
      pumpRepairAck3 = pumpRepairAck3,
      pumpControlRepairAck0 = pumpControlRepairAck0,
      pumpControlRepairAck1 = pumpControlRepairAck1,
      pumpControlRepairAck2 = pumpControlRepairAck2,
      pumpControlRepairAck3 = pumpControlRepairAck3,
      levelRepairAck = levelRepairAck,
      steamRepairAck = steamRepairAck
    )
  }

  val ad : ArchitectureDescription = {

    ArchitectureDescription(
      components = IS[Art.BridgeId, Bridge] (BoilerControlSystem_i_Instance_bcproc_boiler, BoilerControlSystem_i_Instance_bcproc_pumpControl0, BoilerControlSystem_i_Instance_bcproc_pumpControl1, BoilerControlSystem_i_Instance_bcproc_pumpControl2, BoilerControlSystem_i_Instance_bcproc_pumpControl3, BoilerControlSystem_i_Instance_bcproc_waterMeter, BoilerControlSystem_i_Instance_bcproc_steamMeter, BoilerControlSystem_i_Instance_bcproc_desk, BoilerControlSystem_i_Instance_bcproc_control),

      connections = IS[Art.ConnectionId, UConnection] (Connection(from = BoilerControlSystem_i_Instance_bcproc_boiler.waiting, to = BoilerControlSystem_i_Instance_bcproc_control.boilerWaiting),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_boiler.ready, to = BoilerControlSystem_i_Instance_bcproc_control.boilerReady),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_pumpControl0.pumpOpen, to = BoilerControlSystem_i_Instance_bcproc_control.pumpOpen0),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_pumpControl0.pumpFlow, to = BoilerControlSystem_i_Instance_bcproc_control.pumpFlow0),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_pumpControl0.ready, to = BoilerControlSystem_i_Instance_bcproc_control.pumpControlReady0),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_pumpControl1.pumpOpen, to = BoilerControlSystem_i_Instance_bcproc_control.pumpOpen1),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_pumpControl1.pumpFlow, to = BoilerControlSystem_i_Instance_bcproc_control.pumpFlow1),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_pumpControl1.ready, to = BoilerControlSystem_i_Instance_bcproc_control.pumpControlReady1),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_pumpControl2.pumpOpen, to = BoilerControlSystem_i_Instance_bcproc_control.pumpOpen2),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_pumpControl2.pumpFlow, to = BoilerControlSystem_i_Instance_bcproc_control.pumpFlow2),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_pumpControl2.ready, to = BoilerControlSystem_i_Instance_bcproc_control.pumpControlReady2),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_pumpControl3.pumpOpen, to = BoilerControlSystem_i_Instance_bcproc_control.pumpOpen3),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_pumpControl3.pumpFlow, to = BoilerControlSystem_i_Instance_bcproc_control.pumpFlow3),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_pumpControl3.ready, to = BoilerControlSystem_i_Instance_bcproc_control.pumpControlReady3),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_waterMeter.level, to = BoilerControlSystem_i_Instance_bcproc_control.waterLevel),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_waterMeter.ready, to = BoilerControlSystem_i_Instance_bcproc_control.waterMeterReady),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_steamMeter.rate, to = BoilerControlSystem_i_Instance_bcproc_control.steamRate),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_steamMeter.ready, to = BoilerControlSystem_i_Instance_bcproc_control.steamMeterReady),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.stop, to = BoilerControlSystem_i_Instance_bcproc_control.stop),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpRepair0, to = BoilerControlSystem_i_Instance_bcproc_control.pumpRepair0),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpRepair1, to = BoilerControlSystem_i_Instance_bcproc_control.pumpRepair1),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpRepair2, to = BoilerControlSystem_i_Instance_bcproc_control.pumpRepair2),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpRepair3, to = BoilerControlSystem_i_Instance_bcproc_control.pumpRepair3),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlRepair0, to = BoilerControlSystem_i_Instance_bcproc_control.pumpControlRepair0),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlRepair1, to = BoilerControlSystem_i_Instance_bcproc_control.pumpControlRepair1),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlRepair2, to = BoilerControlSystem_i_Instance_bcproc_control.pumpControlRepair2),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlRepair3, to = BoilerControlSystem_i_Instance_bcproc_control.pumpControlRepair3),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.levelRepair, to = BoilerControlSystem_i_Instance_bcproc_control.levelRepair),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.steamRepair, to = BoilerControlSystem_i_Instance_bcproc_control.steamRepair),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpFailAck0, to = BoilerControlSystem_i_Instance_bcproc_control.pumpFailAck0),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpFailAck1, to = BoilerControlSystem_i_Instance_bcproc_control.pumpFailAck1),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpFailAck2, to = BoilerControlSystem_i_Instance_bcproc_control.pumpFailAck2),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpFailAck3, to = BoilerControlSystem_i_Instance_bcproc_control.pumpFailAck3),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlFailAck0, to = BoilerControlSystem_i_Instance_bcproc_control.pumpControlFailAck0),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlFailAck1, to = BoilerControlSystem_i_Instance_bcproc_control.pumpControlFailAck1),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlFailAck2, to = BoilerControlSystem_i_Instance_bcproc_control.pumpControlFailAck2),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlFailAck3, to = BoilerControlSystem_i_Instance_bcproc_control.pumpControlFailAck3),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.levelFailAck, to = BoilerControlSystem_i_Instance_bcproc_control.levelFailAck),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_desk.steamFailAck, to = BoilerControlSystem_i_Instance_bcproc_control.steamFailAck),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.opMode, to = BoilerControlSystem_i_Instance_bcproc_boiler.opMode),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.opMode, to = BoilerControlSystem_i_Instance_bcproc_pumpControl0.opMode),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.opMode, to = BoilerControlSystem_i_Instance_bcproc_pumpControl1.opMode),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.opMode, to = BoilerControlSystem_i_Instance_bcproc_pumpControl2.opMode),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.opMode, to = BoilerControlSystem_i_Instance_bcproc_pumpControl3.opMode),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.opMode, to = BoilerControlSystem_i_Instance_bcproc_waterMeter.opMode),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.opMode, to = BoilerControlSystem_i_Instance_bcproc_steamMeter.opMode),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.opMode, to = BoilerControlSystem_i_Instance_bcproc_desk.opMode),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.openPump0, to = BoilerControlSystem_i_Instance_bcproc_pumpControl0.openPump),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.openPump1, to = BoilerControlSystem_i_Instance_bcproc_pumpControl1.openPump),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.openPump2, to = BoilerControlSystem_i_Instance_bcproc_pumpControl2.openPump),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.openPump3, to = BoilerControlSystem_i_Instance_bcproc_pumpControl3.openPump),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.ready, to = BoilerControlSystem_i_Instance_bcproc_boiler.programReady),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.ready, to = BoilerControlSystem_i_Instance_bcproc_waterMeter.programReady),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.ready, to = BoilerControlSystem_i_Instance_bcproc_pumpControl0.programReady),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.ready, to = BoilerControlSystem_i_Instance_bcproc_pumpControl1.programReady),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.ready, to = BoilerControlSystem_i_Instance_bcproc_pumpControl2.programReady),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.ready, to = BoilerControlSystem_i_Instance_bcproc_pumpControl3.programReady),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.ready, to = BoilerControlSystem_i_Instance_bcproc_steamMeter.programReady),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.valve, to = BoilerControlSystem_i_Instance_bcproc_boiler.valve),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpFail0, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpFail0),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpFail1, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpFail1),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpFail2, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpFail2),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpFail3, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpFail3),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpControlFail0, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlFail0),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpControlFail1, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlFail1),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpControlFail2, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlFail2),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpControlFail3, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlFail3),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.levelFail, to = BoilerControlSystem_i_Instance_bcproc_desk.levelFail),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.steamFail, to = BoilerControlSystem_i_Instance_bcproc_desk.steamFail),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpRepairAck0, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpRepairAck0),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpRepairAck1, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpRepairAck1),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpRepairAck2, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpRepairAck2),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpRepairAck3, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpRepairAck3),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpControlRepairAck0, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlRepairAck0),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpControlRepairAck1, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlRepairAck1),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpControlRepairAck2, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlRepairAck2),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.pumpControlRepairAck3, to = BoilerControlSystem_i_Instance_bcproc_desk.pumpControlRepairAck3),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.levelRepairAck, to = BoilerControlSystem_i_Instance_bcproc_desk.levelRepairAck),
                                                       Connection(from = BoilerControlSystem_i_Instance_bcproc_control.steamRepairAck, to = BoilerControlSystem_i_Instance_bcproc_desk.steamRepairAck))
    )
  }
}
