// #Sireum

package bc.BoilerControl

import org.sireum._
import bc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@enum object OpMode {
  "Init"
  "Norm"
  "Degr"
  "Resc"
  "Stop"
}

object OpMode_Payload {
  def example(): OpMode_Payload = {
    return OpMode_Payload(BoilerControl.OpMode.byOrdinal(0).get)
  }
}

@datatype class OpMode_Payload(value: BoilerControl.OpMode.Type) extends art.DataContent
