// #Sireum

package bc.BoilerControl

import org.sireum._
import art._
import bc._
import bc.BoilerControl.{SteamMeter_i_bcproc_steamMeter => component}

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@datatype class SteamMeter_i_bcproc_steamMeter_Bridge(
  val id: Art.BridgeId,
  val name: String,
  val dispatchProtocol: DispatchPropertyProtocol,
  val dispatchTriggers: Option[ISZ[Art.PortId]],

  opMode: Port[BoilerControl.OpMode.Type],
  rate: Port[Base_Types.Float_32],
  programReady: Port[art.Empty],
  ready: Port[art.Empty]
  ) extends Bridge {

  val ports : Bridge.Ports = Bridge.Ports(
    dataIns = ISZ[art.UPort](),

    dataOuts = ISZ[art.UPort](),

    eventIns = ISZ[art.UPort](opMode,
                              programReady),

    eventOuts = ISZ[art.UPort](rate,
                               ready)
  )

  val initialization_api : SteamMeter_i_Initialization_Api = {
    val api = SteamMeter_i_Initialization_Api(
      id,
      opMode.id,
      rate.id,
      programReady.id,
      ready.id
    )
    SteamMeter_i_bcproc_steamMeter_Bridge.c_initialization_api = Some(api)
    api
  }

  val operational_api : SteamMeter_i_Operational_Api = {
    val api = SteamMeter_i_Operational_Api(
      id,
      opMode.id,
      rate.id,
      programReady.id,
      ready.id
    )
    SteamMeter_i_bcproc_steamMeter_Bridge.c_operational_api = Some(api)
    api
  }

  val entryPoints : Bridge.EntryPoints =
    SteamMeter_i_bcproc_steamMeter_Bridge.EntryPoints(
      id,

      opMode.id,
      rate.id,
      programReady.id,
      ready.id,

      dispatchTriggers,

      initialization_api,
      operational_api)
}

object SteamMeter_i_bcproc_steamMeter_Bridge {

  var c_initialization_api: Option[SteamMeter_i_Initialization_Api] = None()
  var c_operational_api: Option[SteamMeter_i_Operational_Api] = None()

  @datatype class EntryPoints(
    SteamMeter_i_bcproc_steamMeter_BridgeId : Art.BridgeId,
    opMode_Id : Art.PortId,
    rate_Id : Art.PortId,
    programReady_Id : Art.PortId,
    ready_Id : Art.PortId,
    dispatchTriggers : Option[ISZ[Art.PortId]],
    initialization_api: SteamMeter_i_Initialization_Api,
    operational_api: SteamMeter_i_Operational_Api) extends Bridge.EntryPoints {

    val dataInPortIds: ISZ[Art.PortId] = IS()

    val eventInPortIds: ISZ[Art.PortId] = IS(opMode_Id,
                                             programReady_Id)

    val dataOutPortIds: ISZ[Art.PortId] = IS()

    val eventOutPortIds: ISZ[Art.PortId] = IS(rate_Id,
                                              ready_Id)

    def initialise(): Unit = {
      SteamMeter_i_bcproc_steamMeter_EntryPoint_Companion.pre_initialise()

      // implement the following method in 'component':  def initialise(api: SteamMeter_i_Initialization_Api): Unit = {}
      component.initialise(initialization_api)

      SteamMeter_i_bcproc_steamMeter_EntryPoint_Companion.post_initialise()

      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def compute(): Unit = {
      SteamMeter_i_bcproc_steamMeter_Injection_Service.pre_receiveInput()

      Art.receiveInput(eventInPortIds, dataInPortIds)

      SteamMeter_i_bcproc_steamMeter_EntryPoint_Companion.pre_compute()

      // implement the following in 'component':  def timeTriggered(api: SteamMeter_i_Operational_Api): Unit = {}
      component.timeTriggered(operational_api)

      SteamMeter_i_bcproc_steamMeter_EntryPoint_Companion.post_compute()

      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def activate(): Unit = {
      // implement the following method in 'component':  def activate(api: SteamMeter_i_Operational_Api): Unit = {}
      component.activate(operational_api)
    }

    def deactivate(): Unit = {
      // implement the following method in 'component':  def deactivate(api: SteamMeter_i_Operational_Api): Unit = {}
      component.deactivate(operational_api)
    }

    def finalise(): Unit = {
      // implement the following method in 'component':  def finalise(api: SteamMeter_i_Operational_Api): Unit = {}
      component.finalise(operational_api)
    }

    def recover(): Unit = {
      // implement the following method in 'component':  def recover(api: SteamMeter_i_Operational_Api): Unit = {}
      component.recover(operational_api)
    }

    override
    def testInitialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: SteamMeter_i_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }

    override
    def testCompute(): Unit = {
      Art.receiveInput(eventInPortIds, dataInPortIds)

      // implement the following in 'component':  def timeTriggered(api: SteamMeter_i_Operational_Api): Unit = {}
      component.timeTriggered(operational_api)

      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }
  }
}