// #Sireum
package bc.BoilerControl

import org.sireum._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@msig trait OperatorDesk_i_bcproc_desk_Injection_Provider {
  def pre_receiveInput(): Unit
}

object OperatorDesk_i_bcproc_desk_Injection_Service {

  var providers: MSZ[OperatorDesk_i_bcproc_desk_Injection_Provider] = MSZ()

  def register(provider: OperatorDesk_i_bcproc_desk_Injection_Provider): Unit = {
    providers = providers :+ provider
  }

  def pre_receiveInput(): Unit = {
    for (provider <- providers) {
      provider.pre_receiveInput()
    }
  }
}