// #Sireum

package bc.BoilerControl

import org.sireum._
import bc.RandomLib

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Profile for initialise entrypoint
@record class Boiler_i_bcproc_boiler_Profile (
  val name: String,
  val numTests: Z //number of tests to generate
)

// Profile with generators for incoming ports
@record class Boiler_i_bcproc_boiler_Profile_P(
  val name: String,
  val numTests: Z, // number of tests to generate
  var numTestVectorGenRetries: Z, // number of test vector generation retries
  var api_programReady: RandomLib,
  var api_valve: RandomLib,
  var api_opMode: RandomLib)

// Profile with generators for state variables and incoming ports
@record class Boiler_i_bcproc_boiler_Profile_PS(
  val name: String,
  val numTests: Z, // number of tests to generate
  var numTestVectorGenRetries: Z, // number of test vector generation retries
  var In_Mode: RandomLib,
  var In_ValveOpen: RandomLib,
  var api_programReady: RandomLib,
  var api_valve: RandomLib,
  var api_opMode: RandomLib)
