package isolette.system_tests.monitor1

import org.sireum._
import isolette._
import org.sireum.Random.Impl.Xoshiro256

// Do not edit this file as it will be overwritten if SystemTestArtifactGen is rerun

object Monitor_Subsystem_Outputs_Container_Profile {

  def freshRandomLib: RandomLib = {
    return RandomLib(Random.Gen64Impl(Xoshiro256.create))
  }

  def getDefaultProfile: Monitor_Subsystem_Outputs_Container_Profile = {
    return Monitor_Subsystem_Outputs_Container_Profile (
      name = "Default Monitor_Subsystem_Outputs_Container_Profile Profile",
      numTestVectorGenRetries = 100,

      monitor_status = freshRandomLib,
      alarm_control = freshRandomLib,
      monitor_mode = freshRandomLib
    )
  }
}

case class Monitor_Subsystem_Outputs_Container_Profile (
  var name: String,
  var numTestVectorGenRetries: Z,

  var monitor_status : RandomLib,
  var alarm_control : RandomLib,
  var monitor_mode : RandomLib) extends org.sireum.$internal.MutableMarker {

  def next(): Monitor_Subsystem_Outputs_Container = {
    return Monitor_Subsystem_Outputs_Container (
      monitor_status.nextIsolette_Data_ModelStatusType(),
      alarm_control.nextIsolette_Data_ModelOn_OffType(),
      monitor_mode.nextIsolette_Data_ModelMonitor_ModeType()
    )
  }

  override def $clonable: Boolean = F

  override def $clonable_=(b: Boolean): org.sireum.$internal.MutableMarker = this

  override def $owned: Boolean = F

  override def $owned_=(b: Boolean): org.sireum.$internal.MutableMarker = this

  override def $clone: org.sireum.$internal.MutableMarker = this
}
